spring:
  #数据源
  datasource:
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
#      url: jdbc:mysql://127.0.0.1:3306/diy_bing?serverTimezone=UTC
      url: jdbc:mysql://112.124.54.146:3306/diy_bing?serverTimezone=UTC
      username: root2
      password: 123456
  #服务名称
  application:
    name: diy_bing
  jackson:
    date-format: yyyy-MM-dd
  session:
    timeout: 86400

#服务启动端口
server:
  port: 9090

mybatis-plus:
  mapper-locations: classpath*:/mapper/*Mapper.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
